/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hyungjung Kim (https://sketchfab.com/hyungjungkim)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/low-poly-cloud-81910476b24d4fc5a73c908d6c2a38a2
title: Low Poly Cloud
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Cloud({ ...props }) {
  const myObj = useRef();
  useFrame((state) => {
    myObj.current.rotation.y = state.mouse.x * 0.1;
    //myObj.current.position.y = state.mouse.y * -0.1;
    myObj.current.rotation.x = state.mouse.y * 0.1;
    //myObj.current.position.x = state.mouse.x * -0.1;
  });

  const group = useRef();
  const { nodes, materials } = useGLTF("/cloud.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Scene_-_Root"]}
          ref={myObj}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cloud.gltf");
